name: Node.js Test Runner

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: npm run test
        contains: |-
          # tests 5
          # pass 2
          # fail 3
          # cancelled 0
          # skipped 0
          # todo 0
        expected_result: PASSED